### ISSUE TITLE
Colors/Colors/Info

### ISSUE THREAD

**Issue by ErezBinyamin** [pran01/AlgoVision#11]
For each tab there is a pane on the right that describes the symbols present in the window. Make this panes label consistent across all tabs. Instead of it saying "Colors" for search and sort, while saying "symbols" for pathfinding, have the title be "Key" or "Legend" like it is on academic graphs/tables.

**Comment by pran01** [comment]
Yeah I was thinking the same thing while creating it but could find a word suitable. Any  suggestions other than "key" or "Legend"?

**Comment by ErezBinyamin** [comment]
I think [Legend](https://english.stackexchange.com/questions/11878/legend-or-key) would be most appropriate here, but some alternatives could be...

- guide
- explanation
- glossary
- index
- table of symbols
- cipher
- code
- key

**Comment by pran01** [comment]
I prefer key over legend. I will update it.
